################
### MONITORS ###
################
monitor=,preferred,auto,auto

###################
### MY PROGRAMS ###
###################
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

#################
### AUTOSTART ###
#################
exec-once = blueman-applet
exec-once = waybar

###################
### LOOK AND FEEL ###
###################

general {
    gaps_in = 5
    gaps_out = 12
    border_size = 2

    col.active_border = rgba(192,132,252,1.0)
    col.inactive_border = rgba(42,32,54,0.7)

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    windowrule = opacity 0.9 0.8,match:class 1*
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

animations {
    enabled = yes

    bezier = smooth, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, smooth
    animation = workspaces, 1, 7, smooth, slide
}

###################
### LAYOUTS ###
###################

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = false
}

###################
### INPUT ###
###################

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

###################
### KEYBINDS ###
###################

$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, $menu

bind = $mainMod, right, workspace, +1
bind = $mainMod, left, workspace, -1

bind = $mainMod SHIFT, right, movetoworkspace, +1
bind = $mainMod SHIFT, left, movetoworkspace, -1
bind = ALT SHIFT, D, exec, grimblast copysave area
bind = $mainMod, ESCAPE, killactive
bind = $mainMod, F, fullscreen

###################
### MOUSE ###
###################

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
